import { Raleway } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const raleway = Raleway({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        {children}

        <Script src="https://kit.fontawesome.com/d924478ec2.js" />
      </body>
    </html>
  );
}
